### ISSUE TITLE
VPC-4AZS not actually linking RouteTableAssociation to subnet route table! 

### ISSUE THREAD

**Issue by Danlock** [widdix/aws-cf-templates#124]
TemplateID:  	vpc-4azs.yaml
Region: all

Offending lines 199 to 229.
example

```
  RouteTableAssociationCPrivate:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SubnetCPrivate
      RouteTableId: !Ref RouteTablePrivate
```
should be
```
  RouteTableAssociationCPrivate:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref SubnetCPrivate
      RouteTableId: !Ref RouteTableCPrivate
```
