### ISSUE TITLE
add AWS Health event rule

### ISSUE THREAD

**Issue by sgzijl** [widdix/aws-cf-templates#164]
**(This is an issue tracker! You will probably find an answer to your question on Stack Overflow. If not, use the tag amazon-cloudformation to post your question, and the chances are high that we or someone from the community will point you in the right direction. We are not able to answer your questions via email or the project's issue tracker.)**

**(Override all values in parentheses)**

---

TemplateID: `operations/aws-health.yaml`
Region: any

This is not an issue, but an idea/feature request.

I think it might be useful to add an AWS health notifications template, so that issues and scheduled changes are reported to the `operations/alert` sns topic.

The template could look something like:

```
AWSTemplateFormatVersion: 2010-09-09
Description: 'AWS Health: publish issues and scheduled changes to operations/alert topic'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stacks'
      Parameters:
      - ParentAlertStack
Parameters:
 ParentAlertStack:
    Description: 'Stack name of parent alert stack based on operations/alert.yaml template.'
    Type: String
    Default: ''
Resources:
  CloudWatchEventRule: 
    Type: "AWS::Events::Rule"
    Properties: 
      Description: "send all AWS Health notifications to SNS"
      EventPattern: 
        source: 
          - "aws.health"
      State: "ENABLED"
      Targets: 
        - 
          Arn:
            'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'
          Id: "HealthTopic"
Outputs:
  TemplateID:
    Description: 'template id'
    Value: 'operations/awshealth'
  CloudWatchEventRule:
    Description: 'The created CloudWatch event rule'
    Value: !Ref CloudWatchEventRule
    Export:
      Name: !Sub '${AWS::StackName}-CloudWatchEventRule'
```

Users then get notified when AWS is facing platform issues or schedules a change (eg: RDS maintenance), et cetera.

Let me know what you think...

Greetz, Siert
