### ISSUE TITLE
Filter ECS instance events based on cluster id

### ISSUE THREAD

**Issue by andreaswittig** [widdix/aws-cf-templates#200]
TemplateID: ecs/cluster
Region: any

The `SchedulableContainersRule` triggers for events of any ECS cluster. Should filter only events for the specific ECS cluster instead.

For example:

```
SchedulableContainersRule:
    Type: 'AWS::Events::Rule'
    Properties:
      EventPattern:
        source:
          - aws.ecs
        detail-type:
          - ECS Container Instance State Change
        detail:
          clusterArn:
            - !GetAtt 
              - Cluster
              - Arn
      State: ENABLED
      Targets:
        - Arn: !GetAtt 
            - SchedulableContainersLambda
            - Arn
          Id: lambda
```
