### ISSUE TITLE
[Bug] security/kms-key - Error on KMS Key stack creation with policy.

### ISSUE THREAD

**Issue by PatBriPerso** [widdix/aws-cf-templates#259]
TemplateID: security/kms-key
Region: eu-west-3 (Paris)
---
I receive this error from CloudFormation when I try to create the stack with rds as the Service parameter:

> The new key policy will not allow you to update the key policy in the future. (Service: AWSKMS; Status Code: 400; Error Code: MalformedPolicyDocumentException; Request ID: df8ac002-0e3c-4a49-b23b-3a7ba9e809f5)

Here is the resource for KMS Key in my main CF template:
```
  RdsKmsKey:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Service: rds
      TemplateURL: '../../security/kms-key.yaml'
```

I try to change Service parameter to 'ALL_SERVICES' but I still have the same error.

Is it something I do not understand? A bug? A new check from AWS CF?

Thanks for your help.
