### ISSUE TITLE
[state/elasticache-redis] Impossible to set TransitEncryption to false

### ISSUE THREAD

**Issue by PatBriPerso** [widdix/aws-cf-templates#263]
TemplateID: 'state/elasticache-redis.yaml'
Version: 9.1.0
Region: eu-west-3 (Paris)
---
Hi,

I try to use `state/elasticache-redis` template with this parameter: `TransitEncryption: 'false'` but it fails.
If I do not set the `AuthToken` parameter, CloudFormation says that this parameter is mandatory.
If I set `AuthToken`, CloudFormation gives me an error when creating ReplicationGroup: 

> The AUTH token is only supported when encryption-in-transit is enabled

I solve this problem by adding a default value to `AuthToken` like that:
```
  AuthToken:
    Description: 'Password (16 to 128 characters) used to authenticate against Redis. Requried when TransitEncryption = true. Keep empty to disable password-protection.'
    Type: 'String'
    MaxLength: 128
    Default: ''
```
then I use the template with no `AuthToken` parameter:
```
  Redis:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        ParentVPCStack: !GetAtt 'Vpc.Outputs.StackName'
        ParentClientStack: !GetAtt 'EcsClusterClientSG.Outputs.StackName'
        ParentAlertStack: !GetAtt 'Alert.Outputs.StackName'
        EngineVersion: '5.0.0'
        CacheNodeType: 'cache.t2.micro'
        TransitEncryption: 'false'
      TemplateURL: '../../state/elasticache-redis.yaml'
```
and it creates the Redis instance successfully.

Best regards.
