### ISSUE TITLE
Tag EIP(s)

### ISSUE THREAD

**Issue by ab77** [widdix/aws-cf-templates#272]
TemplateID: vpc/vpc-nat-gateway
Region: all

Not an issue, more of a feature request. Untagged (unnamed) EIPs are ugly and difficult to visually attribute to a stack.

I suggest adding [cfn-generic-custom-resource](https://github.com/ab77/cfn-generic-custom-resource/tree/master/generic_provider) Lambda and then tagging EIPs as follows using custom resources:

```
  TagEIP:
    Type: 'Custom::TagEC2Resource'
    Version: 1.0
    Properties:
      ServiceToken: !Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:generic-custom-resource-provider'
      AgentService: ec2
      AgentType: client
      AgentCreateMethod: create_tags
      AgentDeleteMethod: delete_tags
      AgentCreateArgs:
        Resources:
        - !Sub '${Eip.AllocationId}'
        Tags:
        - Key: 'Name'
          Value: 'foo-bar'
      AgentDeleteArgs:
        Resources:
        - !Sub '${Eip.AllocationId}'
        Tags:
        - Key: 'Name'
          Value: 'foo-bar'
```

The other thing you can do with this is to fix the IPv6 CloudFormation nonsense, where it doesn't allow you to map both IPv4 and IPv6 public IPs to a subnet, e.g.:

```
  VPCSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AssignIpv6AddressOnCreation: true
     ...

  ModifySubnetAttribute:
    Type: 'Custom::SubnetModify'
    Version: 1.0
    Properties:
      ServiceToken: !Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:generic-custom-resource-provider'
      AgentService: ec2
      AgentType: client
      AgentCreateMethod: modify_subnet_attribute
      AgentCreateArgs: !Sub |
        {
          "MapPublicIpOnLaunch": {
              "Value": true
          },
          "SubnetId": "${VPCSubnet}"
        }
```
