### ISSUE TITLE
Jenkins and ECS cluster: ruby version too old

### ISSUE THREAD

**Issue by Ten0** [widdix/aws-cf-templates#287]
TemplateID: `jenkins2-ha-agents`
Region: `eu-west-1`

The jenkins master doesn't start as of today.

I did dig for a while and it seems to be due to [aws-sdk-sqs](https://rubygems.org/gems/aws-sdk-sqs/versions/1.10.0) being updated to version 1.11.0, whose dependency `http-2` requires Ruby version >= 2.1.0, while the `AWS::CloudFormation::Init` installs ruby 2.0.0 (precisely `ruby-2.0.0.648-34.amzn2.0.1.x86_64`).

**Comment by Ten0** [comment]
Fixed it this way:
```
  MasterLC:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          default: !If [HasIAMUserSSHAccess, [awslogs, ssh-access, ruby, mount, install, setup, extras, custom, run], [awslogs, ruby, mount, install, setup, extras, custom, run]]
```
and
```
        ruby:
          packages:
            yum:
              'gcc': []
              'wget': []
          commands:
            'ruby_install':
              command: 'wget -O ruby-install-0.7.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz && tar -xzvf ruby-install-0.7.0.tar.gz && cd ruby-install-0.7.0/ && make install && ruby-install --system ruby && cd /tmp && wget -O rubygems-3.0.3.tgz https://rubygems.org/rubygems/rubygems-3.0.3.tgz && tar -xzvf rubygems-3.0.3.tgz && cd rubygems-3.0.3 && ruby setup.rb && gem install aws-sdk-autoscaling aws-sdk-sqs daemons'
              cwd: '/tmp'
        mount:
          packages:
            yum:
              'nfs-utils': []
```
and similarly for the `AgentLC` (there is one less target in the config set).
I will probably make a PR eventually if the team does not fix it but I set this here for those whose system is critically impaired and need a fix before I create said PR.

Btw, a newer version of jenkins was also released. I was in a hurry so I didn't test it, but you may want to update it as well. (https://pkg.jenkins.io/redhat-stable/jenkins-2.164.1-1.1.noarch.rpm)

**Comment by michaelwittig** [comment]
See #286

**Comment by michaelwittig** [comment]
We also have a comment from AWS why the are breaking existing versions... keep in mind that we pinned the gem version but it still somehow requires a new lib... https://github.com/aws/aws-sdk-ruby/issues/1994

**Comment by egut** [comment]
For ECS: I have temporary removed lifecycle-poller and all its dependency. This let my continue.

BTW What do the lifecycle-poller do? A few comments would be help full :)

**Comment by michaelwittig** [comment]
@egut In the ECS context, it does instance draining. You better do not scale in your cluster if you removed id. A temporary fix is available in PR #268

**Comment by egut** [comment]
@michaelwittig I could not see one specific for the ecs/cluster is the magic sauce:

```
        extras:
          commands:
            'a_enable_docker':
              command: 'amazon-linux-extras enable docker=18.06.1'
              test: "! grep -Fxq '[amzn2extra-docker]' /etc/yum.repos.d/amzn2-extras.repo"
            'b_enable_corretto8':
              command: 'amazon-linux-extras enable corretto8'
              test: "! grep -Fxq '[amzn2extra-corretto8]' /etc/yum.repos.d/amzn2-extras.repo"
```
Do I need to install another ruby too?
