### ISSUE TITLE
AgentIAMRole is not authorized to perform: ssm:ListAssociations on resource

### ISSUE THREAD

**Issue by nkhine** [widdix/aws-cf-templates#348]
**(This is an issue tracker! You will probably find an answer to your question on Stack Overflow. If not, use the tag amazon-cloudformation to post your question, and the chances are high that we or someone from the community will point you in the right direction. We are not able to answer your questions via email or the project's issue tracker.)**

**(Override all values in parentheses)**

---

TemplateID: `jenkins/jenkins2-ha-agents`
Region: `eu-west-1`

Hello,

i am having an issue launching the jenkins-agents, you can check the logs on aws cloudwatch, for example, i get:

```
Sep 4 15:06:23 ip-10-1-40-213 amazon-ssm-agent: 2019-09-04 15:06:23 ERROR [MessagingDeliveryService] [Association] error when calling AWS APIs. error details - AccessDeniedException: User: arn:aws:sts::*****:assumed-role/JenkinsService-*****-AgentIAMRole-GK59I9JP6AON/i-0c4f622fb462440f8 is not authorized to perform: ssm:ListInstanceAssociations on resource: arn:aws:ec2:eu-west-1:*****:instance/i-0c4f622fb462440f8
```

```
Sep 4 15:06:24 ip-10-1-40-213 amazon-ssm-agent: 2019-09-04 15:06:23 ERROR [MessagingDeliveryService] [Association] Unable to load instance associations, unable to retrieve associations unable to retrieve associations AccessDeniedException: User: arn:aws:sts::*****:assumed-role/JenkinsService-*****-AgentIAMRole-GK59I9JP6AON/i-0c4f622fb462440f8 is not authorized to perform: ssm:ListAssociations on resource: arn:aws:ssm:eu-west-1:*****:*
```

so none of the agents get launched.

i am using:

```
  JenkinsService:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ParentVPCStack: !GetAtt VPC.Outputs.StackName
        ParentAlertStack: !GetAtt Alerts.Outputs.StackName
        IAMUserSSHAccess: true
        SystemsManagerAccess: true
        MasterInstanceType: 'm3.large'
        MasterAdminPassword: '*****'
        AgentInstanceType: 'm3.large'
        ParentZoneStack: !GetAtt PublicDNS.Outputs.StackName
      TemplateURL: templates/jenkins/jenkins2-ha-agents.yaml
```

to set the Parameters.

i also modified, https://github.com/widdix/aws-cf-templates/blob/master/jenkins/jenkins2-ha-agents.yaml#L539-L549 and https://github.com/widdix/aws-cf-templates/blob/master/jenkins/jenkins2-ha-agents.yaml#L1440-L1443 to include `ssm:ListAssociations`

```
      Policies:
      - !If
        - HasSystemsManagerAccess
        - PolicyName: ssm
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - 'ssmmessages:*' # SSM Agent by https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up-messageAPIs.html
              - 'ssm:UpdateInstanceInformation' # SSM agent by https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up-messageAPIs.html
              - 'ec2messages:*' # SSM Session Manager by https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up-messageAPIs.html
              - 'ssm:ListAssociations'
              Resource: '*'
```

but i still get the error.

i am able to connect to the ec2 instance without an ssh key as it is using the IAM role for my user.

jenkins-master is deployed as per template, but the `jenkins-agents` fail.

any advice is much appreciated

**Comment by michaelwittig** [comment]
HI @nkhine 
What exactly is your problem? Do you only see error messages from amazon-ssm-agent ? Is Jenkins working? Any CloudFOrmation errors?

**Comment by nkhine** [comment]
hi,
the errors i get are as follows:

```
java.io.IOException: Server returned HTTP response code: 401 for URL: http://10.1.13.10:8080/cli?remoting=false
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:72)
at hudson.cli.CLI.plainHttpConnection(CLI.java:279)
at hudson.cli.CLI._main(CLI.java:271)
at hudson.cli.CLI.main(CLI.java:83)
```

this is from `agent/i-0fe31e96dc66426c5/var/log/cfn-init.log` log, after i increased the agent size to `1` - https://github.com/widdix/aws-cf-templates/blob/master/jenkins/jenkins2-ha-agents.yaml#L175-L177

when i ssh into the jenkins-agent and try to execute the command:

```
[root@ip-10-1-43-90 jenkins]# java -jar jenkins-cli.jar -s http://10.1.13.10:8080 -auth admin:**** create-node i-0fe31e96dc66426c5
java.io.IOException: Server returned HTTP response code: 401 for URL: http://10.1.13.10:8080/cli?remoting=false
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:72)
	at hudson.cli.CLI.plainHttpConnection(CLI.java:279)
	at hudson.cli.CLI._main(CLI.java:271)
	at hudson.cli.CLI.main(CLI.java:83)
```

i am able to login into the jenkins UI using the `admin` user and `password`

**Comment by michaelwittig** [comment]
Have you changed the CloudFormation parameter `MasterAdminPassword` after you created the stack?

**Comment by nkhine** [comment]
the only change, i made was to add SSL to the ELB, as:

```
  # Redirect to SSL
  MasterELBListener: # This is the ALB Listener used to access the Jenkins Master
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: "redirect"
          RedirectConfig:
            Protocol: "HTTPS"
            Port: "443"
            Host: "#{host}"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref MasterELB
      Port: 80
      Protocol: HTTP

  MasterHTTPSListener: # This is the HTTPS ALB Listener used to access the Jenkins Master
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        # - CertificateArn: !Ref CertificateARN
        - CertificateArn: !FindInMap
            - SSLmapping
            - ssl1
            - !FindInMap
              - AWSRegionsNameMapping
              - !Ref 'AWS::Region'
              - RegionName
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref MasterELBTargetGroup
      LoadBalancerArn: !Ref MasterELB
      Port: 443
      Protocol: HTTPS
```

also, when i logged in for the first time, i created a new user, perhaps, this first user should be `admin` with the same `MasterAdminPassword`
