### ISSUE TITLE
Access  Denied for bucket Please  check S3bucket permission (Service: AmazonElasticLoadBalancingV2; Status  Code: 400)

### ISSUE THREAD

**Issue by nkhine** [widdix/aws-cf-templates#349]
**(This is an issue tracker! You will probably find an answer to your question on Stack Overflow. If not, use the tag amazon-cloudformation to post your question, and the chances are high that we or someone from the community will point you in the right direction. We are not able to answer your questions via email or the project's issue tracker.)**

**(Override all values in parentheses)**

---

TemplateID: `jenkins/jenkins-ha-agents`
Region: `eu-west-1`

Hello,

I get the following error, when enabling the `ParentS3StackAccessLog` on the `jenkins` or any other templates

```
  | Access  Denied for bucket:  mw-mgm-elbaccesslogwrites3-****-bucket-****. Please  check S3bucket permission (Service: AmazonElasticLoadBalancingV2; Status  Code: 400; Error Code: InvalidConfigurationRequest; Request ID:  636b4517-d9f5-11e9-ba45-99f17beeaad7)
-- | --
```

this is the code, i have:

```
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ClassB: !Ref ClassB
      TemplateURL: templates/vpc/vpc-2azs.yaml

  S3GatewayEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ParentVPCStack: !GetAtt VPC.Outputs.StackName
      TemplateURL: templates/vpc/vpc-endpoint-s3.yaml

  KMS:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
      #   ParentAlertStack: !GetAtt Alerts.Outputs.StackName
      TemplateURL: templates/security/kms-key.yaml

  ElbAccessLogWriteS3:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ParentKmsKeyStack: !GetAtt KMS.Outputs.StackName
        ParentVpcEndpointStack: !GetAtt S3GatewayEndpoint.Outputs.StackName
        Access: ElbAccessLogWrite
      TemplateURL: templates/state/s3.yaml

  JenkinsService:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ParentVPCStack: !GetAtt VPC.Outputs.StackName
        ParentSSHBastionStack: !GetAtt VPN.Outputs.StackName
        ParentAlertStack: !GetAtt Alerts.Outputs.StackName
        IAMUserSSHAccess: true
        MasterInstanceType: 'm3.medium'
        MasterAdminPassword: '****'
        AgentInstanceType: 'm3.large'
        ParentZoneStack: !GetAtt PublicDNS.Outputs.StackName
        ParentS3StackAccessLog: !GetAtt ElbAccessLogWriteS3.Outputs.StackName
      TemplateURL: templates/jenkins/jenkins-ha-agents.yaml
```

looking at the bucket policy being created, seem it is ok:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::797873946194:root",
                    "arn:aws:iam::600734575887:root",
                    "arn:aws:iam::985666609251:root",
                    "arn:aws:iam::054676820928:root",
                    "arn:aws:iam::652711504416:root",
                    "arn:aws:iam::114774131450:root",
                    "arn:aws:iam::156460612806:root",
                    "arn:aws:iam::582318560864:root",
                    "arn:aws:iam::127311923021:root",
                    "arn:aws:iam::507241528517:root",
                    "arn:aws:iam::897822967062:root",
                    "arn:aws:iam::027434742980:root",
                    "arn:aws:iam::009996457667:root",
                    "arn:aws:iam::383597477331:root",
                    "arn:aws:iam::718504428378:root",
                    "arn:aws:iam::033677994240:root",
                    "arn:aws:iam::783225319266:root"
                ]
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::mw-mgm-elbaccesslogwrites3-**prefix**-bucket-**prefix**/*AWSLogs/myAccountID/*"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "delivery.logs.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::mw-mgm-elbaccesslogwrites3-**prefix**-bucket-**prefix**/*AWSLogs/myAccountID/*",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        },
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "delivery.logs.amazonaws.com"
            },
            "Action": "s3:GetBucketAcl",
            "Resource": "arn:aws:s3:::mw-mgm-elbaccesslogwrites3-**prefix**-bucket-**prefix**"
        }
    ]
}
```

any advice is much appreciated
