### ISSUE TITLE
fargate/service:  Additional Permissions for Task Execution Role

### ISSUE THREAD

**Issue by ambsw-technology** [widdix/aws-cf-templates#357]
TemplateID: `fargate/service-*`
Region: `us-east-1`

Our Fargate Services need both Private Registry Access and SSM Parameter Store access.  According to [the documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_execution_IAM_role.html), these permissions need to be added to the `TaskExecutionRole`.  The  parameter `TaskPolicies` may be used to add permissions to the `TaskRole` but I don't see any way to add permissions to the `TaskExecutionRole`. 

To ensure `TaskPolicies` isn't adequate, I tried adding the permissions there, but am still getting:

> Asm fetching secret from the service for \<secret\> AccessDeniedException: User: \<TaskExecutionRole\> is not authorized to perform: secretsmanager:GetSecretValue on resource: \<secret\> status code: 400, request id: \<id\>

Obviously, we could replicate the `TaskPolicies` approach with a `TaskExecutionPolicies`.  However, I wonder if it wouldn't be better to output `TaskExecutionPolicy.Arn` to give the caller more flexibility.

**Comment by michaelwittig** [comment]
When do you fetch the params from parameter store?

* In the task definition (not supported by the template) to inject a ssm param as an environment variable? `TaskExecutionRole` is what you need to modify.
* In your container? If so, the `TaskRole` with the `TaskPolicies` is what you are looking for.

**Comment by ambsw-technology** [comment]
To even pull the image, I have to get credentials for my private docker repository from Secrets Manager which requires the `TaskExecutionRole`.

You're correct that my in-container Parameter Store permission had to be attached to the `TaskRole`.

**Comment by michaelwittig** [comment]
Adding permissions to TaskExecutionRole will not solve your problem without touching the TaskDefinition? 

1. If I get your use case right, you need to git pull from a private registry that is not ECR, right?
2. And you want to fetch the registry credentials from ssm?

**Comment by ambsw-technology** [comment]
Yes.  Since submitting the ticket, I've made the requisite changes in my fork:

 - [TaskExecutionRoles](https://github.com/ambsw/aws-cf-templates/compare/fargate-service-common...ambsw:fargate-service-task-execution-roles) to pass in the managed policies
 - [AppRepositoryCredentialsARN](https://github.com/ambsw/aws-cf-templates/compare/fargate-service-common...ambsw:fargate-private-repo)

Note that both build on my service consolidation in PR #358.  Neither are totally ready to be PR'd because I need to figure if/out how to extend support to the Proxy and Sidecar containers.

**Comment by ambsw-technology** [comment]
I'm currently building the permissions object for the `RepositoryCredentials` outside of this PR, but a version of it could probably be internalized too:

```
  PrivateRepoRole:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description:  'Access to SSM Parameter Store parameters for the Client'
      Path: '/'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: 'Allow'
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !ImportValue 'APEX-PrivateRepoARN'
          - Effect: 'Allow'
            Action:
              - "kms:Decrypt"
            Resource:
              # Too Permissive, but it can only be applied to the keys to which the user is also authorized
              - !Join
                - ''
                - - 'arn:aws:kms:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !If [HasPrivateRepoAccount, !Ref 'PrivateRepoAccount', !Ref 'AWS::AccountId']
                  - ':key:*'
```

**Comment by natac13** [comment]
So I just got my private Docker hub repo working by using a `ParentDockerLogin` stack. Which is imported into both the `cluster.yml` and `cluster-alb.yml` files. As shown below. I know I have not accounted for the use of CMK.

### cluster.yaml
```yaml
ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  # Allow the ECS Tasks to download images from ECR
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"

                  # Allow the ECS tasks to upload logs to CloudWatch
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  # To allow the Task to work with secrets
                  - "ssm:GetParameters"
                  - "secretsmanager:GetSecretValue"
                Resource:
                  - "*"
                  - {'Fn::ImportValue': !Sub '${ParentDockerHubLoginStack}-DockerLogin'}

```


### dockerloginstack.yaml
```yaml
 
AWSTemplateFormatVersion: 2010-09-09
Description: |
  CF to create a secret for my docker hub account.
Parameters:
  DockerUserName:
    Type: String
    Default: ''
    Description: Docker Hub username for login
  DockerPassword:
    Type: String
    Default: "*******"
    Description: Docker Hub password for login
    NoEcho: true

Resources:
  DockerHubSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: Docker Hub Account Login
      SecretString: !Sub
        - '{"username":"${Username}","password":"${Password}"}'
        - Username: !Ref DockerUserName
          Password: !Ref DockerPassword
      Tags:
        - Key: use
          Value: DockerHub
        - Key: Env
          Value: prod
      Name: !Sub "${AWS::StackName}-Docker-Login"

Outputs:
  DockerLogin:
    Description: DockerHub SecretManager ARN
    Value: !Ref "DockerHubSecret"
    Export:
      Name: !Sub "${AWS::StackName}-DockerLogin"
```

### task definition in alb-cluster.yaml
```yaml
TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - DynamoDBSession
    Properties:
      Family: !Sub "servicename-${Client}"
      Cpu: !FindInMap [CpuMap, !Ref Cpu, Cpu]
      Memory: !FindInMap [MemoryMap, !Ref Memory, Memory]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue: !Sub "${ParentClusterStack}-ECSTaskExecutionRole"
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: name
          Image: !Sub "image:${Version}"
          Essential: true
          RepositoryCredentials:
            CredentialsParameter:
              {
                "Fn::ImportValue": !Sub "${ParentDockerLoginStack}-DockerLogin",
              }
          PortMappings:
            - ContainerPort: !Ref Port
          LogConfiguration:
            LogDriver: awslogs
            Options:
              "awslogs-region": !Ref "AWS::Region"
              "awslogs-group": !Ref LogGroup
              "awslogs-stream-prefix": !Sub "prefix"
          Environment:
            - Name: SERVER_PORT
              Value: !Ref Port
          Secrets:
            - Name: "SECRET"
              ValueFrom: !Sub arn:aws:ssm:us-east-1:${AWS::AccountId}:parameter/<SECRETNAME>
      Tags:
        - Key: Env
          Value: prod
```
