### ISSUE TITLE
`ParentAuthProxyStack`, bastions, and Security Group interfaces

### ISSUE THREAD

**Issue by ambsw-technology** [widdix/aws-cf-templates#366]
TemplateID: `fargate/cluster`, `vpc/vpc-vpn-bastion` and `state/client-sg`

We're setting up a service (fargate cluster) that will only be accessed from an jump box and/or a software VPN server -- for client access over site-to-site VPNs.  Currently, `fargate/cluster` can be exposed to either:

1. The public internet (`HasNotAuthProxySecurityGroup`) or 
1. `ParentAuthProxyStack` which is documented as a `security/auth-proxy-*.yaml` template.

Neither of these defaults are appropriate to our situation, but I had some observations as I was worked through my options for getting this working:

1. While `security/auth-proxy-*` doesn't look like a good fit, it's Security Group interface (`${AWS::StackName}-SecurityGroup`) appears to be compatible with `vpc/vpc-*-bastion`.

    - The `bastion` modules appear to cover both of our actual needs.
    - It seems like both `bastion` and `auth-proxy` provide an inbound proxy behavior and should be interchangeable in many places.
    - I wonder if they could be consolidated under a namespace like `security/proxy-*` so documentation for consumers (like `fargate/cluster`) would more easily capture both options.

2. The `security/auth-proxy-*` interface is not compatible with `state/client-sg` which uses `${AWS::StackName}-ClientSecurityGroup`.  My first thought is that the interfaces should be standardized, but I changed my mind.

   - You don't really want someone passing a `bastion` to other modules (like `fargate/cluster`) since a bastion is supposed to operate as a DMZ of sorts.
   - Probably the better solution is a dedicated `security/proxy-custom` that exposes the same Security Group at both
       - `*-ClientSecurityGroup` so other modules can be used in the custom proxy implementation and 
       - `*-SecurityGroup` so it can be used as a proxy.
   - FWIW I wish the naming were reversed so the `-sg` interface was `*-SecurityGroup` and the proxy interface was `*-ProxySecurityGroup`

I'm new so it's possible that I misunderstand one (or both) of these issues.  I also realize several of my comments are not backwards-compatible.  At the same time, it can be hard to understand the learning curve when you know a package inside and out so hopefully the perspective is valuable.

**Comment by michaelwittig** [comment]
For the `fargate/cluster` template:
If you set the `LoadBalancerScheme` to internal and the `ParentAuthProxyStack` to the stack name of a stack based on `vpc/vpc-vpn-bastion` you can only access the cluster's load balancer via VPN.

Would that be sufficient for you?

**Comment by ambsw-technology** [comment]
Perfect.  That's the direction I was headed.  Do you want a PR that changes the documentation for `fargate/cluster`?

**Comment by ambsw-technology** [comment]
A couple more things that could be documented:

1.  I assume you're aware, but it wasn't obvious to me that `ParentAuthProxyStack` must share the same VPC as the `fargate/cluster` because the `HasAuthProxySecurityGroup...` conditions create Ingress rules using `SourceSecurityGroupId` which only work within a VPC (or peer).

    To avoid the complexity of peers, I'm going to start with a public ALB that only permits ingress from my Bastion IP.  FWIW this works well with existing `vpc-*-bastion` templates because they export an `-IPAddress` that can be used in Ingress rules, but wouldn't work for the current `auth-proxy-*` template which use a scaling group without direct access to an IP address.

2.  It also looks like an `internal` load balancer without a `ParentAuthProxyStack` creates permissions for global public access even though these permissions don't make sense.  It could make sense to filter out this possibility.

===

It looks like the cluster and load balancer have no cross-dependencies within `fargate/cluster`.  While the combined template made it easier to get started, it seems like it introduces unnecessary complexity.  Even the existing options permit some incompatible combinations.

I wonder if it would be cleaner/simpler to have a couple ALB templates (`load-balancer-public`, `load-balancer-proxy`, etc.) and create/inject the one you want into the cluster.  Cluster can still export the ALB at all of the same places (for backwards compatibility), but would require a lot less conditional logic.  For example (excluding most options for clarity):

```
Resources:
  LoadBalancer:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        ParentVPCStack: ..,
        # no ParentAuthProxyStack because it's public
        # no LoadBalancerScheme because it's public
        LoadBalancerCertificateArn: ...
      TemplateURL: './aws-cf-templates/.../load-balancer-public.yaml'
  Cluster:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        # It looks like you only need other params if you don't export them from LoadBalancer
        LoadBalancerStack: !GetAtt 'LoadBalancer.Outputs.StackName'
      TemplateURL: './aws-cf-templates/fargate/cluster.yaml'
```

In this arrangement, it'd be easier to add a Load Balancer template with the features I want without appearing to proliferate `cluster` templates -- especially since the `cluster` part is mostly trivial.
