### ISSUE TITLE
Suggestion: easy resolution of latest EC2 AMI ID

### ISSUE THREAD

**Issue by SiuMingCode** [widdix/aws-cf-templates#418]
According to "Launching latest Amazon Linux AMI in an AWS CloudFormation stack" in https://aws.amazon.com/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/.

One can easily get latest EC2/ECS-optimized AMD ID by
```
Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  # REF: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html
  ECSLatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id'
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      # ...
```

So you no longer need to manually maintain the ids. Great work you guys.
