### ISSUE TITLE
Incorrect test and typo in test for `h_download_jenkins_plugin_manager` step

### ISSUE THREAD

**Issue by digorgonzola** [widdix/aws-cf-templates#619]
Inspect the following line: https://github.com/widdix/aws-cf-templates/blob/f60fb59c90df993c302e7fa3c230c5e5b5954357/jenkins/jenkins2-ha.yaml#L961

There is a typo in the task:
``` yaml
            'h_download_jenkins_plugin_manager':
              command: 'wget --quiet --timeout=60 --output-document=/opt/jenkins-plugin-manager.jar https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.11.0/jenkins-plugin-manager-2.11.0.jar'
              est: '[ ! -f /var/lib/jenkins/setup_done.txt ]'
```

Not only is it a typo but the test is not the correct type for this step. It should be checking for the existence of the plugin manager jar file to see if it needs to download it e.g.:

```test: '[ ! -f /opt/jenkins-plugin-manager.jar ]'```

A better approach would be to use a command that checked for it's existence but also check that it was the correct version e.g. compare the md5sum of the remote and local file first
