### ISSUE TITLE
CloudFront wasn't able to connect to the origin. 

### ISSUE THREAD

**Issue by meldehi** [widdix/aws-cf-templates#68]
Thanks for putting this together.

Using the wordpress template as per documentation.
I am getting the following error when I try to access the cloudfront endpoint:

ERROR

The request could not be satisfied.

CloudFront wasn't able to connect to the origin. 
Generated by cloudfront (CloudFront)

The load balancer endpoint does not seem to load any of the css and photos:
https://wordpress-loadbala-wfc5mq2yz8we-82036775.us-west-2.elb.amazonaws.com

**Comment by meldehi** [comment]
I have changed the SSL Certificate in the cloudFront distribution to Default CloudFront Certificate (*.cloudfront.net) to see if that works.

**Comment by michaelwittig** [comment]
Your load balancer endpoint does not seem to be reachable any longer?

**Comment by meldehi** [comment]
To rule out certificate related issues. I modified the load balancer listeners to listen to http requests on port 80. I have also modified the security group inbound rules to allow the same. Still getting the same thing when. The load balancer is reachable, it loads text but not photos and css. 

I would assume something is wrong with either the wordpress installation or the EFS mounting.

**Comment by tgies** [comment]
@meldehi The load balancer endpoint not loading the CSS and images is because the wordpress code is pointing to https://eldehiry.com and that is not working at present.

I think I understand the main issue because I ran into it too. The problem comes from the stack using a custom ACM certificate on the ELB, then using the Amazon-generated DNS name of that ELB to refer to it from the CloudFront distribution, causing a certificate name mismatch. To work around it I had to create my own DNS record, matching the certificate I had provided for the ELB, and point it to the ELB, then point CloudFront to my newly created DNS name for the ELB. I think another fix would be to simply drop the ACM certificate for the ELB from the stack as it's not needed and is the cause of the problem; this concept works fine using the Amazon-provided default certificate on the ELB.

**Comment by meldehi** [comment]
@tgies, I think you are right, both about the certificate mismatch and the CSS and images.
Creating a hosted zone for my domain and configuring the necessary records got things got things to work correctly.

I think this issue has been resolved. There could be some improvements but I will leave it to the authors :)

**Comment by tgies** [comment]
Can we leave it open, actually? The issue in the template remains and I'd like to see it fixed.

**Comment by meldehi** [comment]
Feel free to reopen

**Comment by kbcaleb** [comment]
I got around this by using a route53 option to allow adding the root (domain.com) and the LB record (lb.domain.com) if needed. This allowed the SSL checks to work correctly on our domains.
```
diff --git a/wordpress/wordpress-ha.yaml b/wordpress/wordpress-ha.yaml
index c8fd092..f17de39 100644
--- a/wordpress/wordpress-ha.yaml
+++ b/wordpress/wordpress-ha.yaml
@@ -36,7 +36,26 @@ Metadata:
         default: 'Database Parameters'
       Parameters:
       - DBServerInstanceType
+    - Label:
+        default: 'Route 53 parameters'
+      Parameters:
+      - 53Domain
+      - 53Record
 Parameters:
+  53Domain:
+    Default: 'false'
+    Type: String
+    AllowedValues:
+      - true
+      - false
+    Description: 'Create Route53 domain record.'
+  53Record:
+    Default: 'false'
+    Type: String
+    AllowedValues:
+      - true
+      - false
+    Description: 'Create Route53 DNS record.'
   ParentVPCStack:
     Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
     Type: String
@@ -142,6 +161,8 @@ Mappings:
     'us-west-2':
       AMI: 'ami-4836a428'
 Conditions:
+  Create53Domain: !Equals [!Ref 53Domain, 'true']
+  Create53Record: !Equals [!Ref 53Record, 'true']
   HasKeyName: !Not [!Equals [!Ref WebServerKeyName, '']]
   HasIAMUserSSHAccess: !Equals [!Ref WebServerIAMUserSSHAccess, 'true']
   HasSSHBastionSecurityGroup: !Not [!Equals [!Ref ParentSSHBastionStack, '']]
@@ -151,6 +172,38 @@ Conditions:
   HasNewRelic: !Not [!Equals [!Ref NewRelicLicenseKey, '']]
   HasAlertTopic: !Not [!Equals [!Ref ParentAlertStack, '']]
 Resources:
+  Route53Domain:
+    Type: AWS::Route53::HostedZone
+    Condition: Create53Domain
+    DependsOn: CloudFrontDistribution
+    Properties:
+      HostedZoneConfig:
+        Comment: !Sub '${DomainName} apex zone'
+      Name: !Sub '${DomainName}'
+  Route53CFRecord:
+    Type: AWS::Route53::RecordSet
+    Condition: Create53Record
+    DependsOn: CloudFrontDistribution
+    Properties:
+      HostedZoneName: !Join ['', [!Sub '${DomainName}', '.']]
+      Comment: ELB zone
+      Name: !Join ['', [!Sub '${DomainName}', '.']]
+      Type: A
+      AliasTarget:
+        HostedZoneId: !Ref CloudFrontDistribution
+        DNSName: !GetAtt CloudFrontDistribution.DomainName
+  Route53ELBRecord:
+    Type: AWS::Route53::RecordSet
+    Condition: Create53Record
+    DependsOn: LoadBalancer
+    Properties:
+      HostedZoneName: !Join ['', [!Sub '${DomainName}', '.']]
+      Comment: ELB zone
+      Name: !Join ['', ['lb.', !Sub '${DomainName}', '.']]
+      Type: A
+      AliasTarget:
+        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneNameID
+        DNSName: !GetAtt LoadBalancer.DNSName
   WebServerLogs:
     Type: 'AWS::Logs::LogGroup'
     Properties:
@@ -481,7 +534,7 @@ Resources:
                     php wp-cli.phar core download --allow-root --version=${BlogVersion}
                     php wp-cli.phar core config --dbname='wordpress' --dbuser='wordpress' --dbpass='wordpress' --dbhost='${Database.Endpoint.Address}' --allow-root
                     php wp-cli.phar core install --url='https://${DomainName}' --title='${BlogTitle}' --admin_user='${BlogAdminUsername}' --admin_password='${BlogAdminPassword}' --admin_email='${BlogAdminEMail}' --skip-email --allow-root
-                    sed -i "/$table_prefix = 'wp_';/a\$_SERVER['HTTPS'] = 'on';" /var/www/html/wp-config.php 
+                    sed -i "/$table_prefix = 'wp_';/a\$_SERVER['HTTPS'] = 'on';" /var/www/html/wp-config.php
                   fi
                   chown -R apache:apache /var/www/html
                   chmod u+wrx /var/www/html/wp-content/*
@@ -705,7 +758,7 @@ Resources:
     Type: AWS::EFS::MountTarget
     Properties:
       FileSystemId: !Ref EFSFileSystem
-      SubnetId: 
+      SubnetId:
         'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetBPublic'
       SecurityGroups:
       - !Ref EFSSecurityGroup
@@ -713,7 +766,7 @@ Resources:
     Type: AWS::EC2::SecurityGroup
     Properties:
       GroupDescription: Allowing access to EFS
-      VpcId: 
+      VpcId:
         'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
       SecurityGroupIngress:
       - IpProtocol: tcp
@@ -812,4 +865,4 @@ Outputs:
     Description: 'The domain name of the CloudFront distribution.'
     Value: !Sub ${CloudFrontDistribution.DomainName}
     Export:
-      Name: !Sub '${AWS::StackName}-CloudFrontDomainName'
\ No newline at end of file
+      Name: !Sub '${AWS::StackName}-CloudFrontDomainName'
```

**Comment by andreaswittig** [comment]
@meldehi Exactly, accessing Wordpress is only possible by using custom domain name (e.g. wordpress.yourdomain.com). Accessing CloudFront or the ELB through their generated domain names (e.g. d111111abcdef8.cloudfront.net) is not possible.

@tgies Can you please explain your issue with the Wordpress template in more detail?

CloudFront is forwarding the `Host` header, the SSL certificate used by the ELB needs to include the custom domain name as well (see [CloudFront documentation](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-https-cloudfront-to-custom-origin.html)).

@kbcaleb Did you setup a CNAME/Alias record for your custom domain name pointing to the CloudFront distribution? Did you create ACM certificates including your custom domain name for the ELB and CloudFront?

**Comment by kbcaleb** [comment]
@andreaswittig Yes I used a Alias record and I have a wildcard ACM certificate I use for both the LB and CF. Then I set the CloudFrontDistribution.DomainName to either the Route53LBRecord or LoadBalancer.DNSName based on condition.

**Comment by andreaswittig** [comment]
@kbcaleb Unfortunately, I was not able to reproduce your issue.

Anyone with a broken setup that I can have a look at?

**Comment by tgies** [comment]
@andreaswittig The origin CloudFront is pointing to is the **load balancer default DNS name.** Meanwhile the load balancer has been configured with an ACM certificate for a **custom DNS name specified during the setup.** This causes CloudFront to experience an SSL error (common name mismatch) when it connects to the **ELB default DNS name** and is presented by the ELB with a certificate for the **custom DNS name** instead. Your template _implies_, but does not do, the extra step of pointing the custom DNS name to the ELB (to match the SSL certificate you have configured it to present) and pointing the CloudFront origin to that custom DNS name.

I am pretty sure you could reproduce this problem by deploying the template in a brand new AWS account with a domain name you haven't preconfigured in any way. I can't see how it could possibly just work out of the box as written and I have tried deploying it on "blank" AWS accounts with various new and existing domains with the same predictable result.

**Comment by michaelwittig** [comment]
@tgies all templates are deployed each week in an automated way. https://github.com/widdix/aws-cf-templates/blob/master/test/src/test/java/de/widdix/awscftemplates/wordpress/TestWordpressHA.java

so I'm pretty sure that it works. The question is why it does not in your case.

**Comment by andreaswittig** [comment]
I'd help me to reproduce the issue if you would provide the outputs of the following commands:

* Replace `<YOUR_REGION>` with the region you are using for your Wordpress infrastructure.
* Replace `<CLOUDFRONT_ACM_CERTIFICATE_ARN>` With the ARN of the ACM Certificate you are using for CloudFront.
* Replace `<ELBN_ACM_CERTIFICATE_ARN>` With the ARN of the ACM Certificate you are using for the load balancer.

```
aws cloudformation describe-stacks --region <YOUR_REGION>
aws acm describe-certificate --certificate-arn <CLOUDFRONT_ACM_CERTIFICATE_ARN> --region us-east-1
aws acm describe-certificate --certificate-arn <ELB_ACM_CERTIFICATE_ARN> --region <YOUR_REGION>
```

Feel free to send me the output to andreas@widdix.de if you prefer instead of using GitHub for communication.

**Comment by zarby** [comment]
Hi @andreaswittig 

I'm attempting to use this template on a fresh AWS account and receiving the same issue as described above. @tgies seems to have replicated the same issue as me. 

It seems to be a certificate issue but not sure how to implement a workaround.

**Comment by andreaswittig** [comment]
@zarby Can you please help me to replicate your issue by providing the following details.

* Replace `<YOUR_REGION>` with the region you are using for your Wordpress infrastructure.
* Replace `<CLOUDFRONT_ACM_CERTIFICATE_ARN>` With the ARN of the ACM Certificate you are using for CloudFront.
* Replace `<ELBN_ACM_CERTIFICATE_ARN>` With the ARN of the ACM Certificate you are using for the load balancer.

```
aws cloudformation describe-stacks --region <YOUR_REGION>
aws acm describe-certificate --certificate-arn <CLOUDFRONT_ACM_CERTIFICATE_ARN> --region us-east-1
aws acm describe-certificate --certificate-arn <ELB_ACM_CERTIFICATE_ARN> --region <YOUR_REGION>
```

Feel free to send me the output to andreas@widdix.de if you prefer instead of using GitHub for communication.

**Comment by zarby** [comment]
Hi @andreaswittig 

I worked it out. It was user error. 

When creating the certs in acm. I created only a wild card entry in the cert. *.Domain does not cover the parent domain itself. By adding both the parent domain and *.domain i managed to get it to work. I deleted the old stack and recreated from scratch just to be sure.

Thanks for the quick reply however!

**Comment by andreaswittig** [comment]
@zarby Perfect, thanks for letting me know.

**Comment by zarby** [comment]
@andreaswittig 

For the cloud front distribution settings, is it possible to have the CNAME alias field populated by the CNAMEs of the certificate that we generate? As the current cloud formation seems to only set the primary domain for what i understand.

Cheers,
Zarby

**Comment by andreaswittig** [comment]
@zarby I do like your idea, but I can't think of a way to populate the CloudFront distribution alternative names based on the ACM with CloudFormation.

**Comment by ma78** [comment]
I was also facing this issue. To fix it, I ended up recreating the certificate for the Cloudfront distribution to have both domain.com and www.domain.com. This was not necessary for the ELB certificate.

**Comment by brando6090** [comment]
I'm currently experiencing this issue on a fresh install. I haven't changed any of the settings as mentioned above by others. I have provided as much information as I knew how to. :)

http://www.engravologist.com/
aws cloudformation describe-stacks --region <us-west-2>

aws acm describe-certificate --certificate-arn <arn:aws:cloudfront::812711909097:distribution/E3KK4DMSU4HJP4> --region us-east-1

aws acm describe-certificate --certificate-arn <arn:aws:acm:us-west-2:812711909097:certificate/cd8df200-e2e3-4b1d-b9c7-90bb60398418> --region <us-west-2>

**Comment by kbcaleb** [comment]
# Expected Behavior
CloudFront can connect to the Origin of "!GetAtt 'LoadBalancer.DNSName" to cache content from EC2 instances behind the LoadBalancer.

# Actual Behavior
CloudFront fails to connect to the Origin becuase of a name mismatch on the SSL certificate. Since you are calling !GetAtt 'LoadBalancer.DNSName' as the Origin and you are setting "OriginProtocolPolicy: 'https-only'" you are getting a failure becuase the check is looking for

https://lbname-123456789.us-region-number.elb.amazonaws.com

But the LoadBalancer is serving port 443 using a custom ACM certificate which cannot have the domain name of *.amazonaws.com in it. Instead the SSL cert returns the domain.com name from the ACM certifiacte and the CloudFront cache pull fails cause of a name mismatch.

# Proposed Fix
Not sure how you might like to best approach this, but I added a option to create Route53 records for domain.com->CloudFrontDistribution and lb.domain.com->LoadBalancer, then set AWS::CloudFront::Distribution:DistributionConfig:Origins:DomainName to the Route53LBRecord to prevent SSL name mismatches.

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-https-dedicated-ip-or-sni.html

## Current
```yaml
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref DomainName
        Comment: !Ref DomainName
        Origins:
        - DomainName: !GetAtt 'LoadBalancer.DNSName'
          Id: elb
          CustomOriginConfig:
            OriginProtocolPolicy: 'https-only'
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: true
            Headers:
            - '*'
            Cookies:
              Forward: all
          TargetOriginId: elb
          ViewerProtocolPolicy: 'redirect-to-https'
          Compress: true
        CacheBehaviors:
        - PathPattern: wp-includes/*
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 900
          MaxTTL: 900
          MinTTL: 900
          ForwardedValues:
            QueryString: true
            Headers:
            - 'Host'
          TargetOriginId: elb
          ViewerProtocolPolicy: 'redirect-to-https'
          Compress: true
        - PathPattern: wp-content/*
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 900
          MaxTTL: 900
          MinTTL: 900
          ForwardedValues:
            QueryString: true
            Headers:
            - 'Host'
          TargetOriginId: elb
          ViewerProtocolPolicy: 'redirect-to-https'
          Compress: true
        Enabled: true
        HttpVersion: http2
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontAcmCertificate
          SslSupportMethod: 'sni-only'
          MinimumProtocolVersion: TLSv1
```
## Proposed
```yaml
  Route53LBRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: LoadBalancer
    Properties:
      HostedZoneName: !Join ['', [!Sub '${DomainName}', '.']]
      Comment: LB zone
      Name: !Join ['', ['lb.', !Sub '${DomainName}', '.']]
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneNameID
  Route53CFRecord:
    Type: AWS::Route53::RecordSet
    Condition: Create53Record
    DependsOn: CloudFrontDistribution
    Properties:
      HostedZoneName: !Join ['', [!Sub '${DomainName}', '.']]
      Comment: CloudFront zone
      Name: !Join ['', [!Sub '${DomainName}', '.']]
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFrontDistribution.DomainName
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref DomainName
        Comment: !Join ['.', [!Ref DomainName, 'lb']]
        Origins:
        - DomainName: !Ref Route53LBRecord
          Id: lb
          CustomOriginConfig:
            OriginProtocolPolicy: 'https-only'
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          ForwardedValues:
            QueryString: true
            Headers:
            - '*'
            Cookies:
              Forward: all
          TargetOriginId: elb
          ViewerProtocolPolicy: 'redirect-to-https'
          Compress: true
        CacheBehaviors:
        - PathPattern: wp-includes/*
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 900
          MaxTTL: 900
          MinTTL: 900
          ForwardedValues:
            QueryString: true
            Headers:
            - 'Host'
          TargetOriginId: elb
          ViewerProtocolPolicy: 'redirect-to-https'
          Compress: true
        - PathPattern: wp-content/*
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          DefaultTTL: 900
          MaxTTL: 900
          MinTTL: 900
          ForwardedValues:
            QueryString: true
            Headers:
            - 'Host'
          TargetOriginId: elb
          ViewerProtocolPolicy: 'redirect-to-https'
          Compress: true
        Enabled: true
        HttpVersion: http2
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref CloudFrontAcmCertificate
          SslSupportMethod: 'sni-only'
          MinimumProtocolVersion: TLSv1
```
