### ISSUE TITLE
`f_install_plugins` not working as expected

### ISSUE THREAD

**Issue by alycda** [widdix/aws-cf-templates#82]
command `f_install_plugins` only installs the first plugin. There is no real documentation on how to install multiple plugins, but the working method is the following:

`java -jar jenkins-cli.jar ... install-plugin plugin-short-name-1 plugin-short-name-2 ...`

see [here](https://issues.jenkins-ci.org/browse/JENKINS-32358).

so the `do...while` statement is not effective. I'm rusty with my bash scripting, so the best solution I can come up with is the following:

```yaml
'f_install_plugins':
  command: java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s "http://localhost:8080/" -noKeyAuth install-plug
in $(echo $(cat /root/plugins.txt)) --username admin --password "$(cat /var/lib/jenkins/secrets/initialAdminPassword)"
  test: '[ ! -f /var/lib/jenkins/setup_done.txt ]'
```
