### ISSUE TITLE
SSM for EC2

### ISSUE THREAD

**Issue by kbcaleb** [widdix/aws-cf-templates#99]
@michaelwittig @andreaswittig What are your thoughts on adding SSM to your templates. I use these often to diagnose/repair boxes when a customer does not have, understand, or has lost bastion access.

- Assign the IAM Policy

```yaml
arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
```

- Add SSM to the configSets

```yaml
ssm:
  commands:
    'a_install_ssm':
      command: 'curl https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm -o /tmp/amazon-ssm-agent.rpm && yum -y install /tmp/amazon-ssm-agent.rpm'
      ignoreErrors: "true"
```

**Comment by michaelwittig** [comment]
sounds good. I think this would be even simpler:

```
ssm:
  packages:
    rpm:
      'amazon-ssm-agen': 'https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm'
```
my only concern is the `latest`. I would prefer to have a fixed version in there.

Final question: Should we make this optional or install on all EC2 instances?
